BlogApp.WebUI/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class BlogModel
    {
    }
}

BlogApp.WebUI/Models/HomeBlogModel.cs
using BlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Models
{
    public class HomeBlogModel
    {
        public List<Blog> SliderBlogs { get; set; }
        public List<Blog> HomeBlogs { get; set; }

    }
}

BlogApp.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository blogRepository;
        private ICategoryRepository categoryRepository;

        public BlogController(IBlogRepository _blogRepo,ICategoryRepository _categoryRepo)
        {
            blogRepository = _blogRepo ;
            categoryRepository = _categoryRepo;

        }

        
        public IActionResult Index(int? id,string q)
        {
            var query = blogRepository.GetAll().Where(i => i.isApproved);

            if (id != null)
            {
                query = query.Where(i => i.CategoryId == id).OrderByDescending(i => i.Date);
            }

            if (!string.IsNullOrEmpty(q))
            {
                query = query.Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q) );
            }

            return View(query);
        }

        public IActionResult List()
        {
            return View(blogRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(),"CategoryId","Name" );
            return View();
        }

        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            entity.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                blogRepository.addBlog(entity);
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories= new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            var blog = blogRepository.GetById(id);
            return View(blog);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    entity.Image = file.FileName;
                }
            

                TempData["message"] = $"{entity.Title} güncellendi ";
                entity.Date = DateTime.Now;
                blogRepository.UpdateBlog(entity);

                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(blogRepository.GetById(id));
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BlogId)
        {
            blogRepository.DeleteBlog(BlogId);
            TempData["message"] = $"The item whos id number is {BlogId} has deleted.";
            return RedirectToAction("List");
        }

        public IActionResult Details(int id)
        {
            return View(blogRepository.GetById(id));
        }


    }
}

BlogApp.WebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository repository;

        public CategoryController(ICategoryRepository _repo)
        {
            repository = _repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(repository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category entity)
        {
            if (ModelState.IsValid)
            {
                repository.addCategory(entity);
                return RedirectToAction("List");
            }

            return View(entity);
        }


    }
}

BlogApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository blogRepository = null;
        private ICategoryRepository categoryRepository = null;

        public HomeController(IBlogRepository _blogrepo, ICategoryRepository _categoryrepo)
        {
            blogRepository = _blogrepo;
            categoryRepository = _categoryrepo;
        }

        public IActionResult Index()
        {
            HomeBlogModel model = new HomeBlogModel();
            model.HomeBlogs = blogRepository.GetAll().Where(i => i.isHome && i.isApproved).ToList();
            model.SliderBlogs = blogRepository.GetAll().Where(i => i.isHome && i.isSlider).ToList();

            return View(model);
        }

        public IActionResult List()
        {
            var allBlogs = blogRepository.GetAll();

            return View(allBlogs);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var requiredBlog = blogRepository.GetById(id);
           
            return View(requiredBlog);
        }

      


    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        private ICategoryRepository categoryRepository;
        public CategoryMenuViewComponent(ICategoryRepository _repo)
        {
            categoryRepository = _repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.selectedCategory = RouteData?.Values["id"];

            return View(categoryRepository.GetAll());
        }

    }
}

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h2>Create Blog</h2>
    <div class="row">
        <div class="col">

            <form method="post" asp-controller="Blog" asp-action="Create">

                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                </div>

                <div class="form-group">
                    <label asp-for="Body"></label>
                    <input asp-for="Body" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control" />
                </div>

                <div class="form-check">
                    <label asp-for="isHome" class="form-check-label">
                        <input asp-for="isHome" class="form-check-input" />
                        is Home
                    </label>
                </div>

                <div class="form-check">
                    <label asp-for="isApproved" class="form-check-label">
                        <input asp-for="isApproved" class="form-check-input" />
                        is Approved
                    </label>
                </div>

                <div class="form-group">
                    <label asp-for="CategoryId"></label>
                    <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                        <option selected disabled value="">Select Category</option>
                    </select>
                </div>

                <input type="submit" value="Submit" class="btn btn-primary" />

            </form>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3><b>@Model.BlogId</b> are you sure about deleting this blog ? </h3>
<br />
<form asp-controller="Blog" asp-action="Delete" method="post" >
    <input type="hidden" asp-for="@Model.BlogId" />
    <input type="submit" value="Submit" class="btn btn-primary" />
</form>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog

@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await  Component.InvokeAsync("CategoryMenu")
        </div>

        <div class="col-md-9">
            <div class="card mb-2">
                <div class="card-header">@Model.Title </div>
                <img class="card-img-top" src="~/img/@Model.Image" alt="@Model.Title" />
                
                <div class="card-block">
                    <h4 class="card-title">@Model.Title</h4>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog

@{
    ViewData["Title"] = "Edit";
}

@section scripts{

    <script src="~/modules/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body");
    </script>
}

<div class="container">
    <h2>Update Blog</h2>
    <div class="row">
        <div class="col">

            <form method="post" asp-controller="Blog" asp-action="Edit" enctype="multipart/form-data">

                <input type="hidden" asp-for="BlogId" />


                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                </div>

                <div class="form-group">
                    <label asp-for="Body"></label>
                    <textarea asp-for="Body" class="form-control"></textarea>
                </div>

                <div class="form-group">
                    <label>Image</label>
                    <input type="file" name="file" id="file" class="form-control" />
                </div>

                <div class="form-check">
                    <label asp-for="isHome" class="form-check-label">
                        <input asp-for="isHome" class="form-check-input" />
                        is Home
                    </label>
                </div>

                <div class="form-check">
                    <label asp-for="isApproved" class="form-check-label">
                        <input asp-for="isApproved" class="form-check-input" />
                        is Approved
                    </label>
                </div>

                <div class="form-group">
                    <label asp-for="CategoryId"></label>
                    <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.Categories">
                        <option disabled value="">Select Category</option>
                    </select>
                </div>

                <input type="submit" value="Submit" class="btn btn-primary" />

            </form>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "Index";
}


<div class="container">

    <div class="row mt-3">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">

            @Html.Partial("_BlogList", Model)

        </div>
    </div>

</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>Blog List</h2>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0 )
            {
                <table class="table table-bordered table-striped " >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>isApproved</th>
                            <th>isHome</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                       @foreach (var item in Model)
                       {
                        <tr>
                            <td>@item.BlogId</td>
                            <td>
                                <img src="~/img/@item.Image" width="100" />
                            </td>
                            <td>@item.Title</td>
                            <td>@item.Date</td>
                            <td>
                                @if (item.isApproved)
                                {
                                    <p>
                                        <span class="badge badge-info">
                                            Approved
                                        </span>
                                    </p>
                                }
                                else
                                {
                                    <p>
                                        <span class="badge badge-danger">
                                            Not Approved
                                        </span>
                                    </p>
                                }
                            </td>
                            <td>
                                @if (item.isHome)
                                {
                                    <p>
                                        <span class="badge badge-info">
                                            Home Blog
                                        </span>
                                    </p>
                                }
                                else
                                {
                                    <p>
                                        <span class="badge badge-danger">
                                            Not Home Blog
                                        </span>
                                    </p>
                                }
                            </td>
                            <td>
                                <a asp-controller="Blog"
                                   class="btn btn-primary btn-sm"
                                   asp-action="Edit"
                                   asp-route-id="@item.BlogId">
                                    Update
                                </a>
                                <a asp-controller="Blog"
                                   class="btn btn-danger btn-sm"
                                   asp-action="Delete"
                                   asp-route-id="@item.BlogId">
                                    Delete
                                </a>
                            </td>
                        </tr>
                       }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    There are no blog on database.
                </div>
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Category/Create.cshtml
@model Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h2>Add new category</h2>

    <div class="row">
        <div class="col">

            <form method="post" asp-controller="Category" asp-action="Create" >

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                </div>

                <input type="submit" value="Submit" class="btn btn-primary" />

            </form>

        </div>
    </div>

</div>

BlogApp.WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>Category List</h2>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped ">
                    <thead>
                        <tr>
                            <th>Category Id</th>
                            <th>Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.Name</td>
                                
                                <td>
                                    <a asp-controller="Category"
                                       class="btn btn-primary btn-sm"
                                       asp-action="Details"
                                       asp-route-id="@item.CategoryId">
                                        Details
                                    </a>
                                    <a asp-controller="Category"
                                       class="btn btn-danger btn-sm"
                                       asp-action="Delete"
                                       asp-route-id="@item.CategoryId">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    No category has been found.
                </div>
            }
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Details.cshtml
@model Blog

@{
    ViewData["Title"] = "Details";
}

    <div class="container">


        <div class="row mt-3">
            <div class="col-md-3">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        Cras justo odio
                    </a>
                    <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                    <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                    <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                    <a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum at eros</a>
                </div>
            </div>

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        @Model.Title
                    </div>
                    <img src="~/img/@Model.Image" class="card-img-top" alt="...">

                    <div class="card-body">
                        <h5 class="card-title">@Model.Title</h5>
                        <p class="card-text">@Model.Description</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>

        </div>

    </div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model HomeBlogModel

@{
    ViewData["Title"] = "Index";
}

  

    <div class="container my-4">

        <div class="row mt-3">
            <div class="col-md-3">
              @await Component.InvokeAsync("CategoryMenu")
            </div>
            <div class="col-md-9">
               @Html.Partial("_Slider",Model.SliderBlogs)
               @Html.Partial("_BlogList",Model.HomeBlogs)

            </div>
        </div>

    </div>

BlogApp.WebUI/Views/Home/List.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "List";
}

<div class="container">

    <div class="row mt-3">

        <div class="col-md-3">
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum at eros</a>
            </div>
        </div>

        <div class="col-md-9">
            @foreach (var item in Model)
            {

                <div class="card mb-2">
                    <div class="card-header">
                        @item.Title
                    </div>
                    <img src="~/img/@item.Image" class="card-img-top" alt="...">

                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">@item.Description </p>
                        <a asp-controller="Home"
                           asp-action="Details"
                           asp-route-id="@item.BlogId"
                           class="btn btn-primary">Details</a>
                    </div>
                </div>
            }
        </div>


        </div>

</div>

BlogApp.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>



    <div class="list-group">

        @foreach (var item in Model)
        {
            <a asp-controller="Blog"
               asp-action="Index"
               asp-route-id="@item.CategoryId"
               class="list-group-item list-group-item-action 
               @(ViewBag.selectedCategory==item.CategoryId.ToString() ? "active":"")
               ">
                @item.Name
            </a>

        }

    </div>

BlogApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link href="~/modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" />

    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User Page<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/List">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/category/list">Category</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div id="main">
        <div class="container mt-3">
            <div class="row">
                <div class="col">

                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-success">
                            @TempData["message"]
                        </div>
                    }

                </div>
            </div>
        </div>

        @RenderBody()
    </div>


    <script src="~/modules/jquery/dist/jquery.min.js"></script>
    <script src="~/modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/node_modules/popper.js/dist/cjs/index.min.js"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

BlogApp.WebUI/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>

@if (Model.Count() == 0)
{
    <div class="alert alert-danger">
        There are no blog on this category.
    </div>
}
else
{
    @foreach (var item in Model)
    {
        <div class="card">
            <div class="card-header">
                @item.Title
            </div>
            <img src="~/img/@item.Image" class="card-img-top" alt="...">

            <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">@item.Description</p>
                <a asp-controller="Blog" asp-action="Details"
                   asp-route-id="@item.BlogId"
                   class="btn btn-primary">Go somewhere</a>
            </div>
        </div>

    }
}

BlogApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link href="~/modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" />

    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container" >
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog">Blog</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    
                </ul>
             
                <partial name="_SearchBox"/>

            </div>
        </div>
    </nav>

    <div id="main">
        <div class="container mt-3">
            <div class="row">
                <div class="col">

                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-success">
                            @TempData["message"]
                        </div>
                    }

                </div>
            </div>
        </div>

        @RenderBody()
    </div>


    <script src="~/modules/jquery/dist/jquery.min.js"></script>
    <script src="~/modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/node_modules/popper.js/dist/cjs/index.min.js"></script>
    <script src="~/js/script.js"></script>

    @RenderSection("scripts",false)


</body>
</html>

BlogApp.WebUI/Views/Shared/_SearchBox.cshtml
<form asp-controller="Blog" asp-action="Index" method="get" class="form-inline my-2 my-lg-0">
    <input id="q" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>